version: '3'

services:
  server:
    build: ../ # todo: change to ghcr image
    ports:
      - 25565:25565
    volumes:
      - ./banned-ips.json:/app/banned-ips.json
      - ./banned-players.json:/app/banned-players.json
      - ./eula.txt:/app/eula.txt
      - ./ops.json:/app/ops.json
      - ./permissions.json:/app/permissions.json
      - ./usercache.json:/app/usercache.json
      - ./whitelist.json:/app/whitelist.json
      - ./plugins:/app/plugins
      - ./world:/app/world
      - ./world_nether:/app/world_nether
      - ./world_the_end:/app/world_the_end

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=your-root-password
      - MYSQL_DATABASE=your-database-name
      - MYSQL_USER=your-username
      - MYSQL_PASSWORD=your-password
    ports:
      - 3307:3306